- name: Add Grafana APT key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  when: grafana_state == 'present'

- name: Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
  when: grafana_state == 'present'

- name: Ensure Grafana is {{ grafana_state }}
  apt:
    name: grafana
    state: "{{ grafana_state }}"
    update_cache: yes
    autoremove: "{{ grafana_state == 'absent' }}"
    purge: "{{ grafana_state == 'absent' }}"
  ignore_errors: "{{ grafana_state == 'absent' }}"

- name: Manage Grafana service
  systemd:
    name: grafana-server
    state: "{{ 'started' if grafana_state == 'present' else 'stopped' }}"
    enabled: "{{ grafana_state == 'present' }}"
  ignore_errors: true

- name: Add Prometheus as a data source to Grafana
  uri:
    url: "{{ grafana_url }}/api/datasources"
    method: POST
    user: "{{ grafana_user }}"
    password: "{{ grafana_password }}"
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "access": "proxy",
        "url": "http://localhost:9090",
        "basicAuth": false,
        "isDefault": true
      }
    status_code: 200
    body_format: json
  when: grafana_state == 'present'

