name: Apply Dev Infra

on:
  push:
    branches:
      - main

jobs:
  apply:
    if: contains(github.event.client_payload.head_commit, 'dev-apply')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Terraform Init & Apply
        working-directory: envs/dev
        run: |
          terraform init
          terraform apply -auto-approve -var-file="dev.tfvars"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
